--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/KygekTeam/KygekClearConsole
build-by-default: true
branches:
  - main
  - pm4
projects:
  KygekClearConsole:
    path: ""
    lint:
      phpstan: false
      directStdout: false
...
