--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/KygekTeam/KygekClearConsole
build-by-default: true
branches:
- main
- pm4
projects:
  KygekClearConsole:
    path: ""
    libs:
    - src: KygekTeam/ktpmpl-cfs/ktpmpl-cfs
      version: ^4.0.0
    lint:
      directStdout: false
...
