---
# Clear server console using command
# Copyright (C) 2021 KygekTeam
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# he Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

name: KygekClearConsole
version: 2.0.0-BETA
description: Clear server console using command
author: KygekTeam
website: "https://github.com/KygekTeam/KygekClearConsole"
api: 4.0.0
extensions:
  Core: ">=8.0"
main: KygekTeam\KygekClearConsole\ClearConsole

commands:
  clearconsole:
    description: Clears server console
    permission: kygekclearconsole.cmd
    aliases: [cc]

# Dummy permission
permissions:
  kygekclearconsole.cmd:
    default: true
...