---
# KygekPluginTemplate plugin configuration file
# Plugin by KygekTeam

# Whether to check for plugin updates (Recommended)
check-updates: true  #// Add this if plugin is planned to be released on Poggit

##### DANGER ZONE #####
# Do not change this (Only for internal use)!
config-version: "1.0"  #// Required, MUST be versioned as "MAJOR.MINOR"
#######################
...